---
title: "vic_crime"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Crimes across various Victorian suburbs

Read all suburb files and combine them into one big data frame
```{r}
df <- data.frame()
files <- c("caufield", "chadstone", "brunswick", "northcote", "coburg", "seddon", "sunshine", "hadfield", "pascoe_vale", "reservoir", "clayton", "box_hill", "sunbury", "preston", "fawkner", "broady", "dandy")
for (f in files) {
  df <- rbind(df, read.csv(paste("./crime/", f, ".csv", sep = ""), sep = "\t"))
}
```
Total number of rows:
```{r}
nrow(df)
```
Columns in the data frame:
```{r}
names(df)
```

The offence divisions are:
```{r}
offence_divisions <- c()
division <- unique(df[,"Offence.Division"])
num_of_divisions <- length(division)
for (i in 1:num_of_divisions) {
  offence_divisions <- c(offence_divisions, levels(division)[i])
}
offence_divisions <- sort(offence_divisions)
offence_divisions
```

The offence subdivisions are:
```{r}
offence_subdivisions <- c()
subdivision <- unique(df[,"Offence.Subdivision"])
num_of_subdivisions <- length(subdivision)
for (i in 1:num_of_subdivisions) {
  offence_subdivisions <- c(offence_subdivisions, levels(subdivision)[i])
}
offence_subdivisions <- sort(offence_subdivisions)
offence_subdivisions
```

The suburbs are:
```{r}
suburbs <- c()
suburb_names <- unique(df[,"Suburb.Town.Name"])
num_of_suburbs <- length(suburb_names)
for (i in 1:num_of_suburbs) {
  suburbs <- c(suburbs, levels(suburb_names)[i])
}
suburbs <- sort(suburbs)
suburbs
```

```{r}
zero_missing_suburb_division <- function (df, year) {
  df$Offence.Subdivision <- NULL
  df$Postcode <- NULL
  for (suburb in suburbs) {
    for (div in offence_divisions) {
      df <- rbind(df, data.frame(Incidents.Recorded = 0, Offence.Division = div, Suburb.Town.Name = suburb, Year.ending.December = year))
    }
  }
  df
}

zero_missing_suburb_subdivision <- function (df, year) {
  df$Offence.Division <- NULL
  df$Postcode <- NULL
  for (suburb in suburbs) {
    for (subdiv in offence_subdivisions) {
      df <- rbind(df, data.frame(Incidents.Recorded = 0, Offence.Subdivision = subdiv, Suburb.Town.Name = suburb, Year.ending.December = year))
    }
  }
  df
}

```

Counts of crime division by suburb for each year:
```{r}
for (year in rev(sort(unique(df$Year.ending.December)))) {
  df_by_year <- df[df$Year.ending.December == year, ]
  df_by_year <- zero_missing_suburb_division(df_by_year, year)
  sum_by_suburb_year <- aggregate(Incidents.Recorded ~ Suburb.Town.Name + Offence.Division, df_by_year, sum)
  stacked_sum <- matrix(sum_by_suburb_year$Incidents.Recorded, nrow = num_of_divisions, ncol = num_of_suburbs, byrow = TRUE)
  
  title <- paste("Total crime division by suburb in", year)
  colours <- c("green", "yellow", "blue", "pink", "red", "forestgreen")
  
  barplot(stacked_sum, names.arg = unique(sum_by_suburb_year$Suburb.Town.Name), col = colours, main = title, las = 2, cex.names = 0.5)
  legend("topleft", rev(as.vector(unique(sum_by_suburb_year$Offence.Division))), fill = rev(colours), cex = 0.5)
}
```

Counts of crime subdivision by suburb for each year:
```{r}
for (year in rev(sort(unique(df$Year.ending.December)))) {
  df_by_year <- df[df$Year.ending.December == year, ]
  df_by_year <- zero_missing_suburb_subdivision(df_by_year, year)
  sum_by_suburb_year <- aggregate(Incidents.Recorded ~ Suburb.Town.Name + Offence.Subdivision, df_by_year, sum)
  stacked_sum <- matrix(sum_by_suburb_year$Incidents.Recorded, nrow = num_of_subdivisions, ncol = num_of_suburbs, byrow = TRUE)
  
  title <- paste("Total crime subdivision by suburb in", year)
  colours <- c("green", "yellow", "blue", "pink", "chocolate", "cyan",
               "red", "chocolate", "hotpink", "lightgreen", "khaki")
  
  barplot(stacked_sum, names.arg = unique(sum_by_suburb_year$Suburb.Town.Name), col = colours, main = title, las = 2, cex.names = 0.5)
  legend("topleft", rev(as.vector(unique(sum_by_suburb_year$Offence.Subdivision))), fill = rev(colours), cex = 0.5)
}
```
